version: '3'
services:
  db:
    container_name: mysql8
    image: mysql:8.0
    # network_mode: host
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
#      MYSQL_USER: sandbox_user
#      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
     - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'

  database:
    image: 'mongo'
    container_name: mongo # give your contatner a name
    environment:
      - MONGO_INITDB_DATABASE=app # database name you want to make
      - MONGO_INITDB_ROOT_USERNAME=root # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=root # set your contatner root password
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./docker/mongo/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
